import { JetBrains_Mono } from 'next/font/google'
import {Providers} from "./providers"
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import './globals.css'

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono" 
});

export const metadata = {
  title: "Portafolio CS",
  descriptions: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable} >
        <main>
          <Providers>
            <NavBar />
            {children}
            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  )
}
